# Generated by Django 5.1.5 on 2025-05-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_department_hospital_doctor_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='success_rate',
            field=models.IntegerField(default=80),
        ),
        migrations.CreateModel(
            name='DoctorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('consultations', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='backend.doctor')),
            ],
        ),
    ]
