# Generated by Django 5.1.5 on 2025-05-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_hospital_success_rate_doctorperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('consultation_type', models.CharField(choices=[('in-person', 'In-Person'), ('video', 'Video')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.doctor')),
            ],
        ),
    ]
